### ISSUE TITLE
Vcf2AvroMR job fails before map-reduce stage

### ISSUE THREAD

**Issue by mh11** [opencb/hpg-bigdata#20]
Running the command with an vcf text file (uncompressed) 
<code>
./build/bin/hpg-bigdata.sh variant convert -i hdfs:///my/genome.vcf -o /my/genome.avro.snappy -x deflate --to-avro
</code>
fails with 
<code>
Container id: container_1433243773280_0038_02_000001
Exit code: 1
Stack trace: ExitCodeException exitCode=1: 
        at org.apache.hadoop.util.Shell.runCommand(Shell.java:538)
        at org.apache.hadoop.util.Shell.run(Shell.java:455)
        at org.apache.hadoop.util.Shell$ShellCommandExecutor.execute(Shell.java:715)
        at org.apache.hadoop.yarn.server.nodemanager.DefaultContainerExecutor.launchContainer(DefaultContainerExecutor.java:211)
        at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:302)
        at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:82)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
</code>

**Comment by mh11** [comment]
By reducing the VARIANT_HEADER property string length from 500,000 bytes to 500 bytes, the job finishes (using empty mapper & reducer).

What is the string size limit in setting configuration properties?

**Comment by mh11** [comment]
Pass file name instead - during the setup of the job, the header is read of the file.
