### ISSUE TITLE
Multiple versions of jersey jars

### ISSUE THREAD

**Issue by dapregi** [opencb/hpg-bigdata#57]
Error when starting the server:
$ ./build/bin/hpg-bigdata-local2.sh admin server --port 1042
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/home/dapregi/appl/hpg-bigdata/build/libs/slf4j-log4j12-1.7.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/dapregi/appl/hpg-bigdata/build/libs/slf4j-simple-1.7.21.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
2016-08-11 19:59:07 INFO  log:186 - Logging initialized @1143ms
2016-08-11 19:59:07 INFO  Server:345 - jetty-9.3.6.v20151106
2016-08-11 19:59:07 INFO  ServerConnector:270 - Started ServerConnector@4f9a3314{HTTP/1.1,[http/1.1]}{0.0.0.0:1042}
Exception in thread "main" java.lang.NoSuchMethodError: javax.ws.rs.core.Application.getProperties()Ljava/util/Map;
        at org.glassfish.jersey.server.ApplicationHandler.<init>(ApplicationHandler.java:271)
        at org.glassfish.jersey.servlet.WebComponent.<init>(WebComponent.java:283)
        at org.glassfish.jersey.servlet.ServletContainer.init(ServletContainer.java:167)
        at org.glassfish.jersey.servlet.ServletContainer.init(ServletContainer.java:349)
        at javax.servlet.GenericServlet.init(GenericServlet.java:244)
        at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:626)
        at org.eclipse.jetty.servlet.ServletHolder.initialize(ServletHolder.java:405)
        at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:875)
        at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:346)
        at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:772)
        at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:259)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
        at org.eclipse.jetty.server.Server.start(Server.java:405)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:106)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
        at org.eclipse.jetty.server.Server.doStart(Server.java:372)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.opencb.hpg.bigdata.app.rest.RestServer.start(RestServer.java:70)
        at org.opencb.hpg.bigdata.app.cli.local.AdminCommandExecutor.startRestServer(AdminCommandExecutor.java:54)
        at org.opencb.hpg.bigdata.app.cli.local.AdminCommandExecutor.execute(AdminCommandExecutor.java:42)
        at org.opencb.hpg.bigdata.app.BigDataLocalMain.main(BigDataLocalMain.java:95)

Two versions of jersey in build/libs:
jersey-server-1.9.jar
jersey-server-2.1.jar

**Comment by jtarraga** [comment]
I can't reproduce the error.

$ ./build/bin/hpg-bigdata-local2.sh admin server --port 1042
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/home/jtarraga/appl-gel/hpg-bigdata/build/libs/slf4j-log4j12-1.7.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/jtarraga/appl-gel/hpg-bigdata/build/libs/slf4j-simple-1.7.21.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
2016-08-15 13:01:51 INFO  log:186 - Logging initialized @693ms
2016-08-15 13:01:51 INFO  Server:345 - jetty-9.3.6.v20151106
Aug 15, 2016 1:01:51 PM org.glassfish.jersey.server.ApplicationHandler initialize
INFO: Initiating Jersey application, version Jersey: 2.1 2013-07-18 18:14:16...
2016-08-15 13:01:51 INFO  ContextHandler:775 - Started o.e.j.s.ServletContextHandler@70f59913{/,null,AVAILABLE}
2016-08-15 13:01:51 INFO  ServerConnector:270 - Started ServerConnector@2f40e5db{HTTP/1.1,[http/1.1]}{0.0.0.0:1042}
2016-08-15 13:01:51 INFO  Server:397 - Started @1369ms
2016-08-15 13:01:51 INFO  RestServer:71 - REST server started, listening on 1042

**Comment by dapregi** [comment]
Multiple versions of jersey are still appearing in libs:

```
$ ls ./hpg-bigdata/build/libs/jersey*
jersey-client-1.9.jar
jersey-common-2.1.jar
jersey-container-servlet-core-2.1.jar
jersey-media-multipart-2.1.jar
jersey-client-2.22.1.jar
jersey-container-servlet-2.22.2.jar
jersey-core-1.9.jar
jersey-server-2.1.jar
```

The server only starts when removing manually ALL the v1.9 jars:

```
$ rm -rf jersey*1.9*.jar
```

**Comment by jtarraga** [comment]
All jersey dependencies with version 1.9 have been excluded by the following commit:
[08141fca220d0dcf724ac6e37de6eef91af6bb5d](https://github.com/opencb/hpg-bigdata/commit/08141fca220d0dcf724ac6e37de6eef91af6bb5d)
